/* ══════════════════════════════════════════════════════════
   RxLoop — medication reference data
   Loaded by both / (homepage demo) and /app/ (the product).

   RULES FOR THIS FILE — do not relax them:
   1. General safety and adherence guidance only.
   2. NO numeric dosing. Ever. Dose belongs to a clinician who
      knows the patient's weight, age, kidneys and pregnancy status.
   3. Every entry here is a FIRST-PASS DRAFT. Before wide public
      release, a licensed pharmacist must review every English
      entry, and a native-speaking health communicator must review
      each of yo / ha / ig / pcm. The UI flags this to users.
   ══════════════════════════════════════════════════════════ */

window.RX = window.RX || {};

RX.LANGS = [
  { id:'en',  label:'English',         native:'English' },
  { id:'pcm', label:'Nigerian Pidgin', native:'Pidgin' },
  { id:'yo',  label:'Yorùbá',          native:'Yorùbá' },
  { id:'ha',  label:'Hausa',           native:'Hausa' },
  { id:'ig',  label:'Igbo',            native:'Igbo' }
];

/* UI strings, so the whole app switches language — not just the cards */
RX.UI = {
  en:  { f1:'What it is for', f2:'How to take it', f3:'When to get help',
         search:'Search a medicine', learn:'Medicines', report:'Report', remind:'Reminders',
         draft:'Draft translation — pending clinical review',
         nodose:'No dosing figures here — ask a pharmacist',
         offline:'Available offline' },
  pcm: { f1:'Wetin e dey do', f2:'How to take am', f3:'When to find help',
         search:'Find medicine', learn:'Medicine', report:'Report', remind:'Reminder',
         draft:'Draft translation — dem never check am well',
         nodose:'No dose number dey here — ask pharmacist',
         offline:'E dey work offline' },
  yo:  { f1:'Ohun tí ó ń ṣe', f2:'Bí a ṣe ń lò ó', f3:'Ìgbà tí o gbọ́dọ̀ wá ìrànlọ́wọ́',
         search:'Wá oògùn', learn:'Oògùn', report:'Ìròyìn', remind:'Ìránnilétí',
         draft:'Ìtumọ̀ àkọ́kọ́ — a kò tíì ṣàyẹ̀wò rẹ̀',
         nodose:'Kò sí iye ìwọ̀n níbí — bi oníṣègùn',
         offline:'Ó ń ṣiṣẹ́ láìsí ìntánẹ́ẹ̀tì' },
  ha:  { f1:'Abin da yake yi', f2:'Yadda ake sha', f3:'Lokacin neman taimako',
         search:'Nemi magani', learn:'Magunguna', report:'Rahoto', remind:'Tunatarwa',
         draft:'Fassarar farko — ba a tantance ba tukuna',
         nodose:'Babu adadin sha a nan — a tambayi likitan magani',
         offline:'Yana aiki ba tare da yanar gizo ba' },
  ig:  { f1:'Ihe ọ na-eme', f2:'Otu esi aṅụ ya', f3:'Mgbe ị ga-achọ enyemaka',
         search:'Chọọ ọgwụ', learn:'Ọgwụ', report:'Mkpesa', remind:'Ncheta',
         draft:'Ntụgharị mbụ — enyochabeghị ya',
         nodose:'Ọ nweghị ọnụọgụ ọṅụṅụ ebe a — jụọ onye ọgwụ',
         offline:'Ọ na-arụ ọrụ na-enweghị ịntanetị' }
};

RX.MEDS = [
  {
    id:'para', name:'Paracetamol', gen:'Acetaminophen · pain and fever',
    tags:['fever','pain','headache','panadol','acetaminophen'],
    en:{f1:'Brings down fever and eases mild to moderate pain.',
        f2:'Swallow with water. Never take two different products that both contain paracetamol — check cold and flu mixtures, which very often do.',
        f3:'Fever still there after three days, or any pain lasting more than five days. Get help immediately if too much has been taken, even if the person feels fine.'},
    pcm:{f1:'E dey bring fever down and reduce small-to-medium pain.',
        f2:'Swallow am with water. No take two different medicine wey both get paracetamol inside — check catarrh and flu mixture well, plenty of dem get am.',
        f3:'If fever still dey after three days, or pain pass five days. If person take too much, rush go hospital sharp-sharp even if e feel alright.'},
    yo:{f1:'Ó ń mú ibà kúrò, ó sì ń dín ìrora kékeré sí àárín kù.',
        f2:'Mu pẹ̀lú omi. Má ṣe lo oògùn méjì tí àwọn méjèèjì ní paracetamol nínú — ṣàyẹ̀wò oògùn òtútù dáadáa, ọ̀pọ̀ wọn ni ó ní nínú.',
        f3:'Bí ibà kò bá lọ lẹ́yìn ọjọ́ mẹ́ta, tàbí ìrora tí ó ju ọjọ́ márùn-ún lọ. Bí ẹnìkan bá lò ó jù, sáré lọ sí ilé ìwòsàn lẹ́sẹ̀kẹsẹ̀.'},
    ha:{f1:'Yana rage zazzaɓi da sauƙaƙa ciwo mai sauƙi zuwa matsakaici.',
        f2:'A sha da ruwa. Kada a haɗa magunguna biyu daban da dukkansu ke ɗauke da paracetamol — a duba magungunan mura sosai, yawancinsu suna da shi.',
        f3:'Idan zazzaɓi bai sauka ba bayan kwana uku, ko ciwo ya wuce kwana biyar. Idan an sha fiye da kima, a garzaya asibiti nan take.'},
    ig:{f1:'Ọ na-ebelata ahụ ọkụ ma belata mgbu dị nta ruo nke etiti.',
        f2:"Were mmiri ṅụọ ya. Ejila ọgwụ abụọ dị iche nwere paracetamol n'ime ha — lelee ọgwụ oyi nke ọma, ọtụtụ n'ime ha nwere ya.",
        f3:'Ọ bụrụ na ahụ ọkụ akwụsịghị mgbe ụbọchị atọ gasịrị, ma ọ bụ mgbu karịrị ụbọchị ise. Ọ bụrụ na e were ya karịa, gaa ụlọ ọgwụ ozugbo.'}
  },
  {
    id:'amox', name:'Amoxicillin', gen:'Antibiotic · bacterial infection',
    tags:['antibiotic','infection','ampiclox','throat','chest'],
    en:{f1:'An antibiotic for certain bacterial infections. It does nothing at all for colds, flu or most sore throats.',
        f2:'Space the doses evenly and finish the entire course even after you feel well. Stopping early is what breeds resistant bacteria.',
        f3:'Rash, swelling of the face or lips, or trouble breathing — stop and get help immediately. Also return if there is no improvement after three days.'},
    pcm:{f1:'Na antibiotic for some bacteria infection. E no fit do anything for catarrh, flu or most throat pain.',
        f2:'Space the dose well-well and finish the whole course even after you don feel better. Na to stop am early dey make bacteria strong pass medicine.',
        f3:'If rash show, face or lip swell, or breathing hard you — stop and find help sharp-sharp. Come back too if nothing change after three days.'},
    yo:{f1:'Antibiotic fún àwọn àkóràn bakitéríà kan. Kò ní ipa kankan lórí òtútù tàbí ọ̀fun dídùn.',
        f2:'Pín àkókò rẹ̀ dọ́gba, kí o sì parí gbogbo rẹ̀ bí ara rẹ tilẹ̀ ti yá. Dídúró lásìkò ni ó ń mú kí bakitéríà lágbára ju oògùn lọ.',
        f3:'Bí ara bá yun, bí ojú tàbí ètè bá wú, tàbí mímí bá le — dá dúró kí o sì wá ìrànlọ́wọ́ lẹ́sẹ̀kẹsẹ̀. Padà pẹ̀lú bí kò bá sí ìyípadà lẹ́yìn ọjọ́ mẹ́ta.'},
    ha:{f1:'Maganin ƙwayoyin cuta ne na wasu cututtuka. Ba ya aiki ko kaɗan a kan mura ko ciwon maƙogwaro.',
        f2:'A raba lokutan sha daidai, a kuma kammala duka maganin ko da an ji sauƙi. Dakatarwa da wuri shi ke ƙarfafa ƙwayoyin cuta.',
        f3:'Idan an sami kurji, kumburin fuska ko leɓe, ko wahalar numfashi — a daina a nemi taimako nan take. A dawo kuma idan babu sauƙi bayan kwana uku.'},
    ig:{f1:'Ọ bụ ọgwụ nje maka ụfọdụ ọrịa nje. Ọ naghị arụ ọrụ maka oyi ma ọ bụ akpịrị mgbu.',
        f2:"Kesaa oge ọṅụṅụ ya nhata, mechaakwa ya niile ọ bụrụgodi na ahụ dị gị mma. Ịkwụsị n'oge na-eme ka nje sie ike karịa ọgwụ.",
        f3:'Ọ bụrụ na ahụ amalite ịgba mkpụrụ, ihu ma ọ bụ egbugbere ọnụ aza, ma ọ bụ iku ume siri ike — kwụsị ma chọọ enyemaka ozugbo.'}
  },
  {
    id:'act', name:'Artemether–Lumefantrine', gen:'ACT · uncomplicated malaria',
    tags:['malaria','coartem','act','fever','lonart'],
    en:{f1:'First-line treatment for uncomplicated malaria. It is only correct after a test confirms malaria — treating a fever blind wastes the drug and hides the real cause.',
        f2:'Take it with food or something fatty like milk or groundnut, otherwise the body absorbs far too little. Complete every dose in the pack.',
        f3:'Vomiting within an hour of a dose, convulsions, confusion, very dark urine, or a fever that returns after finishing — these need a clinic the same day.'},
    pcm:{f1:'Na the first medicine for ordinary malaria. E only correct after test confirm malaria — to just treat fever anyhow dey waste medicine and dey hide the real problem.',
        f2:'Take am with food or something wey get oil like milk or groundnut, if not body no go absorb am well. Finish every dose inside the pack.',
        f3:'If you vomit within one hour after dose, or convulsion, confusion, very dark urine, or fever come back after you finish — go clinic that same day.'},
    yo:{f1:'Oògùn àkọ́kọ́ fún ibà tí kò le. Ó tọ́ nìkan lẹ́yìn tí àyẹ̀wò bá fi ibà hàn.',
        f2:'Mu ún pẹ̀lú oúnjẹ tàbí ohun tí ó ní òróró bíi wàrà tàbí èpà, bí bẹ́ẹ̀ kọ́ ara kò ní gbà á dáadáa. Parí gbogbo ìwọ̀n tí ó wà nínú àpò náà.',
        f3:'Bí o bá bì láàárín wákàtí kan, tàbí gìrì, ìdàrúdàpọ̀ ọkàn, ìtọ̀ dúdú púpọ̀, tàbí ibà padà lẹ́yìn tí o parí — lọ sí ilé ìwòsàn ní ọjọ́ náà gan-an.'},
    ha:{f1:'Maganin farko na zazzaɓin cizon sauro mara tsanani. Ya dace kawai bayan gwaji ya tabbatar da cutar.',
        f2:'A sha shi tare da abinci ko wani abu mai mai kamar madara ko gyaɗa, in ba haka ba jiki ba zai sha shi sosai ba. A kammala kowane sha a cikin fakitin.',
        f3:"Amai a cikin awa ɗaya bayan sha, farfaɗiya, rikicewar hankali, fitsari mai duhu sosai, ko zazzaɓi ya dawo bayan an gama — a je asibiti a ranar."},
    ig:{f1:'Ọgwụ mbụ maka ịba na-adịghị njọ. Ọ ziri ezi naanị mgbe nnwale gosiri na ọ bụ ịba.',
        f2:'Were nri ma ọ bụ ihe nwere mmanụ dịka mmiri ara ehi ma ọ bụ ahụekere ṅụọ ya, ma ọ bụghị ya ahụ agaghị anara ya nke ọma. Mechaa ọṅụṅụ niile dị na ngwugwu ahụ.',
        f3:"Ọ bụrụ na ị gbọọ agbọ n'ime otu awa, ịda mba, mgbagwoju anya, mmamịrị gbara oji nke ukwuu, ma ọ bụ ahụ ọkụ laghachiri — gaa ụlọ ọgwụ n'otu ụbọchị ahụ."}
  },
  {
    id:'ors', name:'ORS + Zinc', gen:'Oral rehydration · childhood diarrhoea',
    tags:['diarrhoea','ors','zinc','children','dehydration','running stomach'],
    en:{f1:'Replaces the water and salts lost in diarrhoea. This is the treatment that saves the child — the fluid, not an antibiotic.',
        f2:'Mix one sachet into the exact volume of clean water printed on it. Never mix it stronger, never sweeten it, and give small sips continuously. Zinc continues for the full ten to fourteen days.',
        f3:'Sunken eyes, no tears, no urine for many hours, a child too weak to drink, blood in the stool, or diarrhoea past two days — this is an emergency.'},
    pcm:{f1:'E dey replace the water and salt wey body loss for running belle. Na the fluid dey save the pikin, no be antibiotic.',
        f2:'Mix one sachet inside the exact water wey dem write for the pack. No make am strong pass, no add sugar, give small-small sip continuously. Zinc go continue full ten to fourteen days.',
        f3:'If eye don sink, no tears, no urine for many hours, pikin too weak to drink, blood dey inside toilet, or e pass two days — na emergency, run go hospital.'},
    yo:{f1:'Ó ń rọ́pò omi àti iyọ̀ tí ara pàdánù nínú ìgbẹ́ gbuuru. Omi yìí ni ó ń gba ọmọ là, kì í ṣe antibiotic.',
        f2:'Da àpò kan sínú iye omi mímọ́ gẹ́gẹ́ bí a ti kọ ọ́ sí ara rẹ̀. Má ṣe mú kí ó lágbára jù, má ṣe fi ṣúgà kún un, kí o sì máa fún un díẹ̀díẹ̀. Zinc yóò tẹ̀síwájú fún ọjọ́ mẹ́wàá sí mẹ́rìnlá.',
        f3:'Bí ojú bá wọlé, kò sí omijé, kò tọ̀ fún wákàtí púpọ̀, ọmọ kò lè mu omi, ẹ̀jẹ̀ wà nínú ìgbẹ́, tàbí ó ti ju ọjọ́ méjì lọ — pàjáwìrì ni.'},
    ha:{f1:'Yana maye gurbin ruwa da gishirin da jiki ya rasa a zawo. Ruwan ne ke ceton yaro, ba maganin ƙwayoyin cuta ba.',
        f2:'A haɗa buhu ɗaya cikin ruwa mai tsafta daidai gwargwadon abin da aka rubuta. Kada a ƙara ƙarfinsa, kada a sa sukari, a riƙa ba da ɗan kaɗan kullum. Zinc ya ci gaba har kwana goma zuwa goma sha huɗu.',
        f3:"Idan idanu sun nutse, babu hawaye, babu fitsari na sa'o'i da yawa, yaro ya kasa sha, akwai jini a bayan gida, ko ya wuce kwana biyu — gaggawa ce."},
    ig:{f1:"Ọ na-edochi mmiri na nnu ahụ furu efu n'afọ ọsịsa. Ọ bụ mmiri a na-azọpụta nwa ahụ, ọ bụghị ọgwụ nje.",
        f2:"Gwakọta otu akpa n'ime mmiri dị ọcha kwesịrị ekwesị nke edere na ya. Emela ka o sie ike karịa, etinyela shuga, nye ya nta nta oge niile. Zinc na-aga n'ihu ụbọchị iri ruo iri na anọ.",
        f3:'Ọ bụrụ na anya adaa, anya mmiri adịghị, ọ nweghị mmamịrị ruo ọtụtụ awa, nwa ahụ enweghị ike ịṅụ ihe, ọbara dị na nsị, ma ọ bụ ọ gafere ụbọchị abụọ — ọ bụ ihe mberede.'}
  },
  {
    id:'amlo', name:'Amlodipine', gen:'Antihypertensive · daily, long-term',
    tags:['blood pressure','hypertension','bp','heart'],
    en:{f1:'Lowers blood pressure. It works only while it is being taken — high blood pressure has no symptoms, so feeling fine is not a reason to stop.',
        f2:'Take it at the same time every day, with or without food. If a day is missed, take the next dose at its normal time rather than doubling up.',
        f3:'Swelling of the ankles, dizziness on standing, or a very slow pulse are worth reporting. Chest pain or breathlessness needs urgent care.'},
    pcm:{f1:'E dey bring blood pressure down. E only dey work while you dey take am — high BP no get symptom, so make you no stop just because you feel alright.',
        f2:'Take am same time every day, with or without food. If you miss one day, take the next dose for im normal time; no double am.',
        f3:'If ankle swell, head dey turn when you stand up, or heartbeat slow well-well, tell person. Chest pain or breathing wahala na urgent.'},
    yo:{f1:'Ó ń dín ìfúnpá kù. Ó ń ṣiṣẹ́ nìkan nígbà tí a bá ń lò ó — ìfúnpá gíga kò ní àmì, nítorí náà kí ara rẹ yá kọ́ ni ìdí láti dá dúró.',
        f2:'Lò ó ní àkókò kan náà lójoojúmọ́, pẹ̀lú oúnjẹ tàbí láìsí. Bí o bá gbàgbé ọjọ́ kan, lo èyí tí ó tẹ̀lé ní àkókò rẹ̀; má ṣe lo méjì pọ̀.',
        f3:'Bí ẹsẹ̀ bá wú, tàbí orí bá ń yí nígbà tí o bá dìde, sọ fún oníṣègùn. Ìrora àyà tàbí ìṣòro mímí jẹ́ pàjáwìrì.'},
    ha:{f1:'Yana rage hawan jini. Yana aiki ne kawai muddin ana sha — hawan jini ba shi da alama, don haka jin daɗi ba dalilin dainawa ba ne.',
        f2:'A sha a lokaci ɗaya kowace rana, da abinci ko ba tare da shi ba. Idan an manta rana ɗaya, a sha na gaba a lokacinsa; kada a ninka.',
        f3:'Kumburin idon sawu, jiri idan an tashi tsaye, ko bugun zuciya a hankali sosai — a sanar da likita. Ciwon ƙirji ko ƙarancin numfashi na gaggawa ne.'},
    ig:{f1:'Ọ na-ebelata ọbara mgbali elu. Ọ na-arụ ọrụ naanị mgbe a na-aṅụ ya — ọbara mgbali elu enweghị ihe ịrịba ama.',
        f2:"Ṅụọ ya n'otu oge kwa ụbọchị, nwere nri ma ọ bụ na-enweghị. Ọ bụrụ na i chefuru otu ụbọchị, ṅụọ nke ọzọ n'oge ya; ejila abụọ ọnụ.",
        f3:'Nkwụsị ụkwụ, isi ọwụwa mgbe i biliri ọtọ, ma ọ bụ obi na-akụ nwayọọ — gwa dọkịta. Mgbu obi ma ọ bụ nsogbu iku ume bụ ihe mberede.'}
  },
  {
    id:'metf', name:'Metformin', gen:'Type 2 diabetes · daily, long-term',
    tags:['diabetes','sugar','glucose','type 2'],
    en:{f1:'Helps the body use its own insulin better in type 2 diabetes. It works alongside food and movement, not instead of them.',
        f2:'Take it with or just after a meal — this reduces the stomach upset most people get in the first weeks. Do not skip meals while taking it.',
        f3:'Persistent vomiting, deep fast breathing, unusual muscle pain or extreme weakness need same-day care. Shaking, sweating and confusion mean low sugar — take something sweet and get help.'},
    pcm:{f1:'E dey help body use im own insulin well for type 2 diabetes. E dey work with food and exercise, no be instead of dem.',
        f2:'Take am with food or just after you chop — e go reduce the belle wahala wey plenty people dey get for the first weeks. No skip food while you dey take am.',
        f3:'If vomit no gree stop, breathing deep and fast, strange muscle pain or serious weakness — go hospital that day. If you dey shake, sweat and confuse, na low sugar: take something sweet quick and find help.'},
    yo:{f1:'Ó ń ran ara lọ́wọ́ láti lo insulin ara rẹ̀ dáadáa nínú àtọ̀gbẹ irú kejì. Ó ń ṣiṣẹ́ pẹ̀lú oúnjẹ àti eré ìdárayá.',
        f2:'Mu ún pẹ̀lú oúnjẹ tàbí lẹ́yìn oúnjẹ — èyí ń dín ìdààmú inú kù ní àwọn ọ̀sẹ̀ àkọ́kọ́. Má ṣe fo oúnjẹ nígbà tí o bá ń lò ó.',
        f3:'Bíbì tí kò dúró, mímí kíkanjú, ìrora iṣan àjèjì tàbí àìlera gidi — lọ sí ilé ìwòsàn lọ́jọ́ náà. Gbígbọ̀n, làágùn àti ìdàrúdàpọ̀ túmọ̀ sí ṣúgà kékeré: jẹ ohun dídùn kí o sì wá ìrànlọ́wọ́.'},
    ha:{f1:'Yana taimaka wa jiki ya yi amfani da insulin ɗinsa sosai a ciwon sukari na biyu. Yana aiki tare da abinci da motsa jiki.',
        f2:'A sha da abinci ko nan da nan bayan cin abinci — hakan yana rage damuwar ciki da mutane da yawa ke ji a makonnin farko. Kada a bar cin abinci yayin shansa.',
        f3:'Amai mara tsayawa, numfashi mai zurfi da sauri, ciwon tsoka mara saba ko matsanancin rauni — a je asibiti a ranar. Rawar jiki, gumi da rikicewa na nufin ƙarancin sukari: a sha wani abu mai zaki a nemi taimako.'},
    ig:{f1:'Ọ na-enyere ahụ aka iji insulin nke ya nke ọma na ọrịa shuga ụdị abụọ. Ọ na-arụ ọrụ ya na nri na mmega ahụ.',
        f2:'Were nri ma ọ bụ mgbe i risịrị nri ṅụọ ya — nke a na-ebelata nsogbu afọ ọtụtụ mmadụ na-enweta n\'izu mbụ. Adịghị agafe nri mgbe ị na-aṅụ ya.',
        f3:'Ịgbọ agbọ na-akwụsịghị, iku ume ọsọ ọsọ, mgbu akwara na-adịghị mma ma ọ bụ ike ọgwụgwụ — gaa ụlọ ọgwụ n\'ụbọchị ahụ. Ịma jijiji, ọsụsọ na mgbagwoju anya pụtara shuga dara ala: rie ihe ụtọ ma chọọ enyemaka.'}
  },
  {
    id:'ibu', name:'Ibuprofen', gen:'NSAID · pain, swelling, fever',
    tags:['pain','fever','swelling','nsaid','period pain','brufen'],
    en:{f1:'Eases pain, brings down fever and reduces swelling — useful where paracetamol alone is not enough.',
        f2:'Always take it with food or just after eating, never on an empty stomach. Do not combine it with diclofenac, aspirin or any other anti-inflammatory, and avoid it entirely if you have an ulcer, kidney disease, or are late in pregnancy.',
        f3:'Black tarry stools, vomiting blood, severe stomach pain, swelling of the face, or passing much less urine than usual — stop and get help the same day.'},
    pcm:{f1:'E dey reduce pain, bring fever down and reduce swelling — e dey useful where paracetamol alone no do.',
        f2:'Always take am with food or just after you chop, no take am for empty belle. No mix am with diclofenac, aspirin or any other anti-inflammatory. If you get ulcer, kidney problem, or you don far for pregnancy, no take am at all.',
        f3:'Black toilet like tar, vomit wey get blood, serious belle pain, face swell, or you no dey urinate like before — stop am and find help that same day.'},
    yo:{f1:'Ó ń dín ìrora kù, ó ń mú ibà kúrò, ó sì ń dín wíwú kù — ó wúlò níbi tí paracetamol nìkan kò tó.',
        f2:'Máa lò ó pẹ̀lú oúnjẹ tàbí lẹ́yìn oúnjẹ, kì í ṣe lórí ikùn òfìfo. Má ṣe lò ó pẹ̀lú diclofenac tàbí aspirin. Bí o bá ní egbò inú, àìsàn kíndìnrín, tàbí o ti pẹ́ nínú oyún, má ṣe lò ó rárá.',
        f3:'Ìgbẹ́ dúdú bí ọ̀dà, èébì tí ó ní ẹ̀jẹ̀, ìrora inú tí ó le, ojú wíwú, tàbí ìtọ̀ tí ó dín kù gidigidi — dá dúró kí o sì wá ìrànlọ́wọ́ lọ́jọ́ náà.'},
    ha:{f1:'Yana rage ciwo, zazzaɓi da kumburi — yana da amfani inda paracetamol kaɗai bai isa ba.',
        f2:'A sha shi da abinci ko nan da nan bayan cin abinci, kada a sha a kan komai a ciki. Kada a haɗa shi da diclofenac ko aspirin. Idan kana da gyambon ciki, cutar koda, ko kina ƙarshen ciki, kada ka sha shi ko kaɗan.',
        f3:'Bayan gida baƙi kamar kwalta, amai mai jini, ciwon ciki mai tsanani, kumburin fuska, ko fitsari ya ragu sosai — a daina a nemi taimako a ranar.'},
    ig:{f1:'Ọ na-ebelata mgbu, ahụ ọkụ na ọzụzụ — ọ bara uru ebe paracetamol naanị ya ezughị.',
        f2:"Were nri ṅụọ ya mgbe niile, ọ bụghị n'afọ efu. Ejikọtala ya na diclofenac ma ọ bụ aspirin. Ọ bụrụ na ị nwere ọnya afọ, ọrịa akụrụ, ma ọ bụ ị dị ime ogologo oge, aṅụla ya ma ọlị.",
        f3:'Nsị ojii dịka kolta, agbọ nwere ọbara, mgbu afọ siri ike, ihu ịza, ma ọ bụ mmamịrị belatara nke ukwuu — kwụsị ma chọọ enyemaka n\'ụbọchị ahụ.'}
  },
  {
    id:'metro', name:'Metronidazole', gen:'Antimicrobial · Flagyl',
    tags:['flagyl','infection','amoeba','dental','stomach','antibiotic'],
    en:{f1:'Treats specific infections caused by amoeba, giardia and certain bacteria — including some dental, abdominal and vaginal infections. It does nothing for ordinary stomach upset.',
        f2:'Take it with food and finish the whole course. Do not drink any alcohol during the course or for two days after it — the combination causes violent vomiting, flushing and a racing heart.',
        f3:'Numbness or tingling in the hands or feet, severe dizziness, fits, or a rash — stop and get help.'},
    pcm:{f1:'E dey treat some infection wey amoeba, giardia and some bacteria dey cause — including some teeth, belle and private-part infection. E no fit do anything for ordinary belle upset.',
        f2:'Take am with food and finish the whole course. No drink any alcohol while you dey take am, and for two days after — the mix go make you vomit well-well, body go dey hot and heart go dey beat fast.',
        f3:'If hand or leg dey numb or dey tingle, serious dizziness, convulsion, or rash — stop and find help.'},
    yo:{f1:'Ó ń wo àwọn àkóràn kan tí amoeba, giardia àti bakitéríà kan ń fà — títí kan àkóràn eyín, inú àti abẹ́. Kò ní ipa lórí ìdààmú inú lásán.',
        f2:'Mu ún pẹ̀lú oúnjẹ, kí o sì parí gbogbo rẹ̀. Má ṣe mu ọtí kankan nígbà tí o bá ń lò ó tàbí fún ọjọ́ méjì lẹ́yìn rẹ̀ — àdàpọ̀ náà ń fa èébì líle, ara gbígbóná àti ọkàn tí ń lù kánkán.',
        f3:'Ọwọ́ tàbí ẹsẹ̀ tí ó ń rọ tàbí ń ta, ojú tí ń yí gidigidi, gìrì, tàbí ara yíyun — dá dúró kí o sì wá ìrànlọ́wọ́.'},
    ha:{f1:'Yana maganin wasu cututtukan da amoeba, giardia da wasu ƙwayoyin cuta ke haifarwa — har da na haƙori, ciki da farji. Ba ya aiki a kan damuwar ciki na yau da kullum.',
        f2:'A sha da abinci a kuma kammala duka maganin. Kada a sha barasa yayin shan sa ko kwana biyu bayan sa — haɗin yana haifar da amai mai tsanani, zafin jiki da bugun zuciya mai sauri.',
        f3:'Suma ko ƙaiƙayi a hannu ko ƙafa, jiri mai tsanani, farfaɗiya, ko kurji — a daina a nemi taimako.'},
    ig:{f1:'Ọ na-agwọ ụfọdụ ọrịa nke amoeba, giardia na ụfọdụ nje na-akpata — gụnyere nke ezé, afọ na ebe nzuzo. Ọ naghị arụ ọrụ maka afọ mgbu nkịtị.',
        f2:'Were nri ṅụọ ya ma mechaa ya niile. Aṅụla mmanya ọ bụla mgbe ị na-aṅụ ya ma ọ bụ ụbọchị abụọ mgbe ị mechara — nchikota ahụ na-akpata agbọ siri ike, ahụ ọkụ na obi na-akụ ọsọ ọsọ.',
        f3:'Aka ma ọ bụ ụkwụ na-anwụ anwụ, isi ọwụwa siri ike, ịda mba, ma ọ bụ mkpụrụ ahụ — kwụsị ma chọọ enyemaka.'}
  },
  {
    id:'cotri', name:'Co-trimoxazole', gen:'Antibiotic · Septrin',
    tags:['septrin','antibiotic','infection','chest','urine','hiv'],
    en:{f1:'An antibiotic for certain chest, urinary and other infections. It is also given daily, long-term, to prevent infections in people living with HIV.',
        f2:'Drink plenty of water while taking it and finish the whole course. Tell whoever dispenses it if you have ever reacted badly to a sulfa medicine.',
        f3:'Any rash at all — especially with fever, blisters, or sores in the mouth or eyes — stop immediately and get help the same day. Also report a sore throat with fever, or unusual bruising.'},
    pcm:{f1:'Na antibiotic for some chest, urine and other infection. Dem dey also give am every day, for long time, to prevent infection for people wey dey live with HIV.',
        f2:'Drink plenty water while you dey take am and finish the whole course. Tell the person wey give you am if sulfa medicine don ever react for your body.',
        f3:'Any rash at all — especially with fever, blister, or sore for mouth or eye — stop am sharp-sharp and find help that same day. Report throat pain with fever, or strange body mark too.'},
    yo:{f1:'Antibiotic fún àwọn àkóràn àyà, ìtọ̀ àti òmíràn. A tún ń fún ni lójoojúmọ́ fún ìgbà pípẹ́ láti dènà àkóràn fún àwọn tí ó ní HIV.',
        f2:'Mu omi púpọ̀ nígbà tí o bá ń lò ó, kí o sì parí gbogbo rẹ̀. Sọ fún ẹni tí ó fún ọ ní oògùn bí oògùn sulfa bá ti ṣe ọ́ ní ìpalára rí.',
        f3:'Ara yíyun kankan — pàápàá pẹ̀lú ibà, roro, tàbí egbò ní ẹnu tàbí ojú — dá dúró lẹ́sẹ̀kẹsẹ̀ kí o sì wá ìrànlọ́wọ́ lọ́jọ́ náà.'},
    ha:{f1:'Maganin ƙwayoyin cuta ne na wasu cututtukan ƙirji, fitsari da sauransu. Ana kuma ba da shi kullum na dogon lokaci don hana cututtuka ga masu ɗauke da HIV.',
        f2:'A sha ruwa mai yawa yayin shan sa a kuma kammala duka maganin. A gaya wa wanda ya ba ka shi idan maganin sulfa ya taɓa cutar da kai.',
        f3:'Duk wani kurji — musamman tare da zazzaɓi, ƙuraje, ko gyambo a baki ko ido — a daina nan take a nemi taimako a ranar.'},
    ig:{f1:'Ọ bụ ọgwụ nje maka ụfọdụ ọrịa obi, mmamịrị na ndị ọzọ. A na-enyekwa ya kwa ụbọchị ogologo oge iji gbochie ọrịa maka ndị nwere HIV.',
        f2:'Ṅụọ mmiri buru ibu mgbe ị na-aṅụ ya ma mechaa ya niile. Gwa onye nyere gị ya ma ọ bụrụ na ọgwụ sulfa emerụtụla gị ahụ.',
        f3:"Mkpụrụ ahụ ọ bụla — karịsịa ya na ahụ ọkụ, mkpụrụ mmiri, ma ọ bụ ọnya n'ọnụ ma ọ bụ anya — kwụsị ozugbo ma chọọ enyemaka n'ụbọchị ahụ."}
  },
  {
    id:'iron', name:'Ferrous sulphate + folic acid', gen:'Iron · anaemia and pregnancy',
    tags:['anaemia','iron','pregnancy','blood','folic acid','tiredness'],
    en:{f1:'Replaces iron and folate, most often in anaemia and during pregnancy. Folic acid early in pregnancy also protects the baby\'s spine.',
        f2:'Take it with a source of vitamin C such as orange, and keep tea, milk and antacids at least an hour away — they block absorption. Your stools will turn black, which is normal and not bleeding.',
        f3:'Keep these tablets locked away from children: a handful can kill a small child. If a child swallows any, treat it as an emergency immediately, even if the child seems fine.'},
    pcm:{f1:'E dey replace iron and folate, mostly for anaemia and for pregnancy. Folic acid for early pregnancy dey protect the baby back-bone too.',
        f2:'Take am with something wey get vitamin C like orange, and keep tea, milk and antacid at least one hour away — dem dey block am. Your toilet go turn black; na normal, no be blood.',
        f3:'Lock these tablets away from pikin: small handful fit kill small child. If pikin swallow any, na emergency — rush hospital immediately even if the pikin look alright.'},
    yo:{f1:'Ó ń rọ́pò irin àti folate, pàápàá nínú àìtó ẹ̀jẹ̀ àti nígbà oyún. Folic acid ní ìbẹ̀rẹ̀ oyún tún ń dáàbò bo ẹ̀yìn ọmọ.',
        f2:'Mu ún pẹ̀lú ohun tí ó ní vitamin C bíi ọsàn, kí o sì fi tíì, wàrà àti antacid sílẹ̀ fún wákàtí kan — wọ́n ń dí i lọ́wọ́. Ìgbẹ́ rẹ yóò di dúdú; ó jẹ́ àbùdá, kì í ṣe ẹ̀jẹ̀.',
        f3:'Tọ́jú àwọn tábìlẹ́tì wọ̀nyí kúrò lọ́wọ́ àwọn ọmọdé: díẹ̀ lè pa ọmọ kékeré. Bí ọmọ bá gbé e mì, pàjáwìrì ni — sáré lọ sí ilé ìwòsàn lẹ́sẹ̀kẹsẹ̀.'},
    ha:{f1:'Yana maye gurbin ƙarfe da folate, musamman a ƙarancin jini da lokacin ciki. Folic acid a farkon ciki yana kuma kare kashin bayan jariri.',
        f2:'A sha da abin da ke da vitamin C kamar lemu, a nisanta shayi, madara da antacid akalla awa ɗaya — suna hana shan sa. Bayan gida zai zama baƙi; wannan na al\'ada ne, ba jini ba.',
        f3:'A ajiye waɗannan kwayoyi nesa da yara: kaɗan na iya kashe ƙaramin yaro. Idan yaro ya haɗiye, gaggawa ce — a garzaya asibiti nan take.'},
    ig:{f1:'Ọ na-edochi ígwè na folate, karịsịa na ọbara ọgbụgba na oge ime. Folic acid na mmalite ime na-echebekwa ọkpụkpụ azụ nwa.',
        f2:'Were ihe nwere vitamin C dịka oroma ṅụọ ya, ma wepụ tii, mmiri ara ehi na antacid opekempe otu awa — ha na-egbochi ya. Nsị gị ga-agba oji; nke ahụ bụ ihe nkịtị, ọ bụghị ọbara.',
        f3:'Debe mkpụrụ ọgwụ ndị a ebe ụmụaka na-agaghị eru: obere ole na ole nwere ike igbu nwatakịrị. Ọ bụrụ na nwa elodaa ya, ọ bụ ihe mberede — gaa ụlọ ọgwụ ozugbo.'}
  },
  {
    id:'salb', name:'Salbutamol inhaler', gen:'Reliever · asthma and wheeze',
    tags:['asthma','inhaler','ventolin','wheeze','breathing','chest'],
    en:{f1:'Opens the airways within minutes during asthma or wheezing. It relieves an attack — it does not prevent the next one.',
        f2:'Shake it, breathe all the way out, then press and breathe in slowly and deeply, and hold your breath about ten seconds. A spacer gets far more of the medicine into the lungs, especially for children.',
        f3:'If you need it more than twice a week, your asthma is not controlled — you need a preventer, so see a clinician. If puffs bring no relief, you cannot finish a sentence, or lips turn blue, that is an emergency.'},
    pcm:{f1:'E dey open the airway within minutes during asthma or wheezing. E dey relieve attack — e no dey prevent the next one.',
        f2:'Shake am, breathe out finish, then press and breathe in slowly and deep, hold your breath like ten seconds. Spacer dey carry plenty of the medicine reach lungs, especially for pikin.',
        f3:'If you need am pass two times for one week, your asthma no dey controlled — you need preventer, go see doctor. If puff no bring relief, you no fit finish one sentence, or lips turn blue, na emergency.'},
    yo:{f1:'Ó ń ṣí ojú ọ̀nà ẹ̀mí sílẹ̀ láàárín ìṣẹ́jú díẹ̀ nígbà ikọ́ fóóforo. Ó ń tú ìkọlù sílẹ̀ — kò dènà èyí tí ó tẹ̀lé.',
        f2:'Mì ín, mí jáde tán, lẹ́yìn náà tẹ̀ ẹ́ kí o sì mí wọlé jẹ́jẹ́ tí ó jinlẹ̀, kí o dì í mú fún ìṣẹ́jú àáyá mẹ́wàá. Spacer ń mú kí oògùn púpọ̀ dé ẹ̀dọ̀fóró, pàápàá fún ọmọdé.',
        f3:'Bí o bá ń lò ó ju ẹ̀ẹ̀mejì lọ ní ọ̀sẹ̀ kan, ikọ́ rẹ kò wà lábẹ́ ìdarí — lọ sí ọ̀dọ̀ oníṣègùn. Bí kò bá tù ọ́ lára, bí o kò lè parí gbólóhùn kan, tàbí ètè bá di búlúù — pàjáwìrì ni.'},
    ha:{f1:'Yana buɗe hanyar iska cikin minti kaɗan lokacin asma. Yana sauƙaƙa harin — ba ya hana na gaba.',
        f2:'A girgiza shi, a fitar da numfashi sarai, sannan a matsa a shaƙa a hankali da zurfi, a riƙe numfashi kusan daƙiƙa goma. Spacer yana kai maganin cikin huhu sosai, musamman ga yara.',
        f3:'Idan kana buƙatarsa fiye da sau biyu a mako, asma ba a sarrafa ba — a je wurin likita. Idan babu sauƙi, ba za ka iya kammala jimla ba, ko leɓe ya zama shuɗi — gaggawa ce.'},
    ig:{f1:'Ọ na-emeghe ụzọ ikuku n\'ime nkeji ole na ole n\'oge ụkwara ume. Ọ na-eweta ahụ iru ala — ọ naghị egbochi nke ọzọ.',
        f2:'Kwa ya, kuwe ume niile pụọ, mgbe ahụ pịa ya ma kuwe ume nwayọọ nke miri emi, jide ume ruo ihe dịka sekọnd iri. Spacer na-eme ka ọgwụ karịa banye n\'akụkụ ume, karịsịa maka ụmụaka.',
        f3:'Ọ bụrụ na ị chọrọ ya karịa ugboro abụọ n\'izu, ejighị ụkwara gị aka — gaa hụ dọkịta. Ọ bụrụ na ọ dịghị enye ahụ iru ala, ị enweghị ike ikwucha ahịrịokwu, ma ọ bụ egbugbere ọnụ na-acha anụnụ anụnụ — ọ bụ ihe mberede.'}
  },
  {
    id:'tb', name:'TB treatment (RHZE)', gen:'Tuberculosis · fixed-dose combination',
    tags:['tb','tuberculosis','cough','rifampicin','isoniazid','chest'],
    en:{f1:'The standard combination that cures tuberculosis. It only works if every single dose is taken for the full number of months prescribed.',
        f2:'Take it once a day, usually on an empty stomach, and keep every clinic appointment. Your urine, tears and sweat will turn orange-red — that is expected and harmless. Never stop when you start feeling better at two or three months.',
        f3:'Yellow eyes or skin, dark urine with vomiting, changes in your vision or colour sight, or numbness in the hands and feet — go to the clinic the same day. Stopping early is how drug-resistant TB is created, and that form is far harder to survive.'},
    pcm:{f1:'Na the standard combination wey dey cure tuberculosis. E only work if you take every single dose for the full months wey dem prescribe.',
        f2:'Take am once a day, usually for empty belle, and no miss any clinic appointment. Your urine, tears and sweat go turn orange-red — na expected, e no dey harm. Never stop when you start feel better for two or three months.',
        f3:'Yellow eye or skin, dark urine with vomiting, your eyesight or colour vision change, or hand and leg dey numb — go clinic that same day. To stop early na wetin dey create drug-resistant TB, and that one hard well-well to survive.'},
    yo:{f1:'Àdàpọ̀ oògùn tí ó ń wo ikọ́ ẹ̀gbẹ. Ó ń ṣiṣẹ́ nìkan bí a bá lo gbogbo ìwọ̀n fún gbogbo oṣù tí a yàn.',
        f2:'Lò ó lẹ́ẹ̀kan lóòjọ́, ní ìgbà púpọ̀ lórí ikùn òfìfo, kí o sì lọ sí gbogbo ìpàdé ilé ìwòsàn. Ìtọ̀, omijé àti òógùn rẹ yóò di ọsàn-pupa — ó jẹ́ àbùdá, kò léwu. Má ṣe dúró nígbà tí ara bá bẹ̀rẹ̀ sí yá ní oṣù méjì tàbí mẹ́ta.',
        f3:'Ojú tàbí awọ tí ó di àwọ̀ ewé, ìtọ̀ dúdú pẹ̀lú èébì, ìyípadà ìríran tàbí àwọ̀, tàbí ọwọ́ àti ẹsẹ̀ tí ń rọ — lọ sí ilé ìwòsàn lọ́jọ́ náà. Dídúró láìtètè parí ni ó ń fa ikọ́ ẹ̀gbẹ tí kò gbọ́ oògùn.'},
    ha:{f1:'Haɗin magungunan da ke warkar da tarin fuka. Yana aiki ne kawai idan an sha kowane sha har tsawon watannin da aka rubuta.',
        f2:'A sha sau ɗaya a rana, galibi a kan komai a ciki, a kuma kiyaye duk ganawar asibiti. Fitsari, hawaye da gumi za su zama ja-orange — hakan al\'ada ne, ba shi da illa. Kada a daina lokacin da aka fara jin sauƙi bayan wata biyu ko uku.',
        f3:'Idanu ko fata sun yi rawaya, fitsari mai duhu tare da amai, canjin gani ko launi, ko suma a hannu da ƙafa — a je asibiti a ranar. Dakatarwa da wuri shi ke haifar da tarin fuka mai jure magani.'},
    ig:{f1:'Ọ bụ nchikota ọgwụ na-agwọ ụkwara nta. Ọ na-arụ ọrụ naanị ma ọ bụrụ na a ṅụrụ ọṅụṅụ ọ bụla ruo ọnwa niile e dere.',
        f2:"Ṅụọ ya otu ugboro n'ụbọchị, ọtụtụ mgbe n'afọ efu, ma gaa nzukọ ụlọ ọgwụ niile. Mmamịrị, anya mmiri na ọsụsọ gị ga-acha oroma-uhie — nke ahụ bụ ihe a tụrụ anya ya, ọ dịghị njọ. Akwụsịla mgbe ahụ malitere ịdị mma n'ọnwa abụọ ma ọ bụ atọ.",
        f3:'Anya ma ọ bụ akpụkpọ ahụ na-acha odo odo, mmamịrị gbara ọchịchịrị na agbọ, mgbanwe n\'ọhụụ gị, ma ọ bụ aka na ụkwụ na-anwụ — gaa ụlọ ọgwụ n\'ụbọchị ahụ. Ịkwụsị n\'oge na-akpata ụkwara nta na-eguzogide ọgwụ.'}
  },
  {
    id:'art', name:'ART (dolutegravir-based)', gen:'HIV treatment · daily, lifelong',
    tags:['hiv','art','arv','dolutegravir','tld','viral load'],
    en:{f1:'Holds HIV down so the immune system recovers and the virus becomes undetectable — at which point it cannot be passed on sexually. It is taken for life, not for a course.',
        f2:'Take it at the same time every day, with or without food, and keep taking it when you feel completely well. Collect the refill before the last tablets run out; a gap of days lets resistance build.',
        f3:'A rash with fever, yellow eyes, or severe abdominal pain need same-day care. If you have missed several days, do not double up — contact your clinic for advice on restarting.'},
    pcm:{f1:'E dey hold HIV down so that body defence go recover and the virus go become undetectable — for that point e no fit pass to another person through sex. Na for life you dey take am, no be course.',
        f2:'Take am same time every day, with or without food, and continue even when you feel completely alright. Collect refill before the last tablet finish; gap of some days dey allow resistance build.',
        f3:'Rash with fever, yellow eye, or serious belle pain need same-day care. If you don miss several days, no double am — call your clinic make dem advise you how to restart.'},
    yo:{f1:'Ó ń kó HIV mọ́lẹ̀ kí ara lè gbógun, kí fáírọ́ọ̀sì náà má sì hàn mọ́ — nígbà náà kò lè tàn kálẹ̀ nípasẹ̀ ìbálòpọ̀. A ń lò ó fún ìgbésí ayé, kì í ṣe fún àkókò kúkúrú.',
        f2:'Lò ó ní àkókò kan náà lójoojúmọ́, pẹ̀lú oúnjẹ tàbí láìsí, kí o sì máa lò ó nígbà tí ara rẹ bá tilẹ̀ yá pátápátá. Gba tuntun kí èyí tí ó kù tó tán.',
        f3:'Ara yíyun pẹ̀lú ibà, ojú tí ó di àwọ̀ ewé, tàbí ìrora inú líle — lọ sí ilé ìwòsàn lọ́jọ́ náà. Bí o bá ti fo ọjọ́ púpọ̀, má ṣe lo méjì pọ̀ — pe ilé ìwòsàn fún ìtọ́sọ́nà.'},
    ha:{f1:'Yana danne HIV don garkuwar jiki ta warke kuma ƙwayar cuta ta ɓace daga gwaji — a lokacin ba za ta iya yaɗuwa ta hanyar jima\'i ba. Ana sha shi na tsawon rai, ba na wani ɗan lokaci ba.',
        f2:'A sha a lokaci ɗaya kowace rana, da abinci ko ba tare da shi ba, a ci gaba ko da an ji lafiya sosai. A karɓi sabon kafin na ƙarshe ya ƙare.',
        f3:'Kurji tare da zazzaɓi, idanu rawaya, ko ciwon ciki mai tsanani — a je asibiti a ranar. Idan an manta kwanaki da yawa, kada a ninka — a tuntuɓi asibiti.'},
    ig:{f1:"Ọ na-ejide HIya n'ala ka ahụ nwee ike ịlụ ọgụ ma mee ka nje ahụ ghara ịpụta na nnwale — n'oge ahụ ọ gaghị agafe site na mmekọahụ. A na-aṅụ ya ogologo ndụ, ọ bụghị maka obere oge.",
        f2:"Ṅụọ ya n'otu oge kwa ụbọchị, nwere nri ma ọ bụ na-enweghị, ma nọgide na-aṅụ ya mgbe ahụ dị gị mma kpamkpam. Nara nke ọhụrụ tupu nke ikpeazụ agwụ.",
        f3:'Mkpụrụ ahụ na ahụ ọkụ, anya na-acha odo odo, ma ọ bụ mgbu afọ siri ike — gaa ụlọ ọgwụ n\'ụbọchị ahụ. Ọ bụrụ na i chefuru ọtụtụ ụbọchị, ejila abụọ ọnụ — kpọọ ụlọ ọgwụ gị.'}
  },
  {
    id:'tram', name:'Tramadol', gen:'Opioid painkiller · prescription only',
    tags:['tramadol','pain','opioid','painkiller','dependence'],
    en:{f1:'A strong prescription painkiller for short-term severe pain. It is not a stamina aid, an energy tablet, or something to take for everyday aches — those uses are where the harm in this country is concentrated.',
        f2:'Take it only as a clinician prescribed, for as short a time as possible. Never combine it with alcohol, sedatives or codeine syrups. Stopping suddenly after weeks of use causes withdrawal, so a clinician should taper it.',
        f3:'Slow or shallow breathing, extreme drowsiness, blue lips, fits, or confusion are an overdose emergency — get help immediately. If you find you cannot get through a day without it, that is dependence and it is treatable; ask for help without shame.'},
    pcm:{f1:'Na strong prescription painkiller for serious pain wey no go tey. E no be stamina medicine, no be energy tablet, and no be for ordinary body pain — na those uses cause most of the wahala for this country.',
        f2:'Take am only as doctor prescribe, and for the shortest time possible. Never mix am with alcohol, sedative or codeine syrup. If you don dey take am for weeks, no just stop sharp — make doctor reduce am small-small.',
        f3:'Slow or shallow breathing, serious sleepiness, blue lips, convulsion, or confusion na overdose emergency — find help immediately. If you no fit pass one day without am, na dependence, and dem fit treat am; ask for help, no shame dey there.'},
    yo:{f1:'Oògùn ìrora líle tí oníṣègùn gbọ́dọ̀ kọ. Kì í ṣe oògùn agbára, kì í sì í ṣe fún ìrora ojoojúmọ́ — ìlò bẹ́ẹ̀ ni ó ń fa ìpalára jùlọ ní orílẹ̀-èdè yìí.',
        f2:'Lò ó gẹ́gẹ́ bí oníṣègùn ṣe kọ nìkan, fún àkókò kúkúrú. Má ṣe da á pọ̀ mọ́ ọtí, oògùn oorun tàbí sìírọ́pù codeine. Bí o bá ti lò ó fún ọ̀sẹ̀ púpọ̀, má ṣe dá dúró lójijì — jẹ́ kí oníṣègùn dín in kù díẹ̀díẹ̀.',
        f3:'Mímí tí ó lọ́ra, oorun àṣejù, ètè búlúù, gìrì, tàbí ìdàrúdàpọ̀ ọkàn jẹ́ pàjáwìrì — wá ìrànlọ́wọ́ lẹ́sẹ̀kẹsẹ̀. Bí o kò bá lè lo ọjọ́ kan láìsí i, ìgbẹ́kẹ̀lé ni, a sì lè tọ́jú rẹ̀; béèrè fún ìrànlọ́wọ́ láìtijú.'},
    ha:{f1:'Maganin ciwo mai ƙarfi da likita kaɗai ke rubutawa, na ciwo mai tsanani na ɗan lokaci. Ba maganin ƙarfi ba ne, ba kuma na ciwon yau da kullum ba — irin wannan amfani shi ke haifar da mafi yawan illa a wannan ƙasa.',
        f2:'A sha yadda likita ya rubuta kawai, na ɗan gajeren lokaci. Kada a haɗa shi da barasa, maganin barci ko sirop na codeine. Idan an sha shi makonni, kada a daina kwatsam — likita ya rage a hankali.',
        f3:'Numfashi a hankali ko mara zurfi, matsanancin barci, leɓe shuɗi, farfaɗiya, ko rikicewa gaggawa ce ta yawan sha — a nemi taimako nan take. Idan ba za ka iya wuce rana ba tare da shi ba, jaraba ce, ana kuma iya magance ta; a nemi taimako ba tare da kunya ba.'},
    ig:{f1:"Ọ bụ ọgwụ mgbu siri ike nke dọkịta ga-ede, maka mgbu dị njọ nke obere oge. Ọ bụghị ọgwụ ike, ọ bụghịkwa maka mgbu ahụ kwa ụbọchị — ojiji dị otú ahụ bụ ebe ọtụtụ mmerụ ahụ dị na obodo a.",
        f2:'Ṅụọ ya naanị otú dọkịta si dee, ruo obere oge. Ejikọtala ya na mmanya, ọgwụ ụra ma ọ bụ sirop codeine. Ọ bụrụ na ị ṅụọla ya izu ole na ole, akwụsịla ya na mberede — ka dọkịta belata ya nwayọọ.',
        f3:'Iku ume nwayọọ ma ọ bụ na-emighị emi, ụra karịrị akarị, egbugbere ọnụ na-acha anụnụ anụnụ, ịda mba, ma ọ bụ mgbagwoju anya bụ ihe mberede nke ịṅụ karịa — chọọ enyemaka ozugbo. Ọ bụrụ na ị chọpụta na ị nweghị ike ịgafe otu ụbọchị na-enweghị ya, nke ahụ bụ ndabere, a pụkwara ịgwọ ya; rịọ maka enyemaka na-enweghị ihere.'}
  }
];

/* Observable red flags on a pack. Deliberately things a person can
   see, smell or price — no lab equipment required. */
RX.FLAGS = [
  'Packaging print is blurred or misaligned',
  'Seal broken or blister loose',
  'Tablets differ in colour, smell or texture',
  'No effect after a full course',
  'Price far below normal',
  'Expiry or batch code missing or unreadable'
];

RX.STATES = ['Rivers','Lagos','Kano','FCT Abuja','Oyo','Anambra','Kaduna','Enugu','Delta','Borno','Other'];
